#!/usr/bin/env bash
# vendor-circuitjs.sh — fetch and vendor the CircuitJS simulator for offline use.
#
# Why this exists: the canonical CircuitJS source repo (pfalstad/circuitjs1)
# does NOT check in its GWT-compiled output. Building from source requires JDK + Ant,
# which we explicitly do not want as a dependency for this project (see
# .project-memory/decisions/vendor-circuitjs-locally.md).
#
# Strategy: download the already-compiled GWT bundle that Paul Falstad publishes
# on https://www.falstad.com/circuit/ . That site is the canonical authoritative
# deployment of CircuitJS. We pull:
#   - circuitjs.html (entry point)
#   - lz-string.min.js (URL decompression helper)
#   - circuitjs106/ (the GWT permutation directory — nocache.js + 5 cache.js files)
#   - font/ (fontello icon font)
#   - manifest.json
# We also pull COPYING.txt (GPLv2 license) from the source repo so the license
# travels with the vendored artifacts.
#
# Usage:
#   bash scripts/vendor-circuitjs.sh           # populate if missing
#   bash scripts/vendor-circuitjs.sh --force   # delete + repopulate
#
# Project policy: public/circuitjs/ is gitignored. We commit only this script
# plus public/circuitjs/.gitkeep (with instructions). LICENSE.txt + NOTICE.txt
# are regenerated by this script on every run so they always match the snapshot.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="$REPO_ROOT/public/circuitjs"
UPSTREAM="https://www.falstad.com/circuit"
SOURCE_REPO_RAW="https://raw.githubusercontent.com/pfalstad/circuitjs1/master"
GWT_DIR="circuitjs106"

FORCE=0
for arg in "$@"; do
  case "$arg" in
    --force|-f) FORCE=1 ;;
    -h|--help)
      grep -E '^# ' "$0" | sed 's/^# //'
      exit 0
      ;;
  esac
done

if [[ -f "$DEST/circuitjs.html" && -d "$DEST/$GWT_DIR" && $FORCE -eq 0 ]]; then
  echo "vendor-circuitjs: $DEST already populated (use --force to refetch)."
  exit 0
fi

# Verify curl is available (no JDK/Ant required — that's the point).
command -v curl >/dev/null || { echo "ERROR: curl is required"; exit 1; }

if [[ $FORCE -eq 1 && -d "$DEST" ]]; then
  echo "vendor-circuitjs: --force given, wiping $DEST"
  rm -rf "$DEST"
fi

mkdir -p "$DEST/$GWT_DIR" "$DEST/font" "$DEST/circuits"

fetch() {
  # fetch <relative-path-under-upstream> <local-dest>
  local rel="$1" out="$2"
  local url="$UPSTREAM/$rel"
  echo "  GET $url"
  curl -fsSL "$url" -o "$out"
}

echo "vendor-circuitjs: fetching from $UPSTREAM ..."

# Entry HTML + sibling helper script.
fetch "circuitjs.html"      "$DEST/circuitjs.html"
fetch "lz-string.min.js"    "$DEST/lz-string.min.js"
fetch "manifest.json"       "$DEST/manifest.json"
fetch "iframe.html"         "$DEST/iframe.html" || true

# GWT compiled bundle. The nocache.js script names the 5 permutation files.
fetch "$GWT_DIR/circuitjs1.nocache.js" "$DEST/$GWT_DIR/circuitjs1.nocache.js"

# Static assets the GWT runtime fetches at load time (style + setup list +
# clear gif + GWT 'clean' theme). Discovered via real Playwright probe — the
# bundle 404s on these if we miss them.
fetch "$GWT_DIR/style.css"        "$DEST/$GWT_DIR/style.css"
fetch "$GWT_DIR/setuplist.txt"    "$DEST/$GWT_DIR/setuplist.txt"
fetch "$GWT_DIR/clear.cache.gif"  "$DEST/$GWT_DIR/clear.cache.gif"
mkdir -p "$DEST/$GWT_DIR/gwt/clean/images"
fetch "$GWT_DIR/gwt/clean/clean.css" "$DEST/$GWT_DIR/gwt/clean/clean.css"
for img in hborder.png vborder.png corner.png hborder_ie6.png vborder_ie6.png; do
  fetch "$GWT_DIR/gwt/clean/images/$img" "$DEST/$GWT_DIR/gwt/clean/images/$img" || true
done

# Rewrite manifest path from upstream /circuit/ to our /circuitjs/ vendor path.
if grep -q '/circuit/manifest.json' "$DEST/circuitjs.html"; then
  sed -i 's|/circuit/manifest.json|/circuitjs/manifest.json|g' "$DEST/circuitjs.html"
fi

# Strip the service-worker registration block entirely. The SW script itself
# isn't vendored (CircuitJS works without it) and trying to register would
# print a noisy 404 in every embed.
if grep -q "navigator.serviceWorker.register" "$DEST/circuitjs.html"; then
  python3 - <<PY
import re, pathlib
html = pathlib.Path("$DEST/circuitjs.html").read_text()
html = re.sub(r"<script>\s*if \('serviceWorker' in navigator\).*?</script>",
              "<script>/* service-worker registration removed by vendor-circuitjs.sh */</script>",
              html, count=1, flags=re.DOTALL)
pathlib.Path("$DEST/circuitjs.html").write_text(html)
PY
  echo "vendor-circuitjs: removed service-worker registration"
fi

# Extract permutation hashes from nocache.js and pull each .cache.js.
mapfile -t PERMS < <(grep -oE '[A-F0-9]{32}' "$DEST/$GWT_DIR/circuitjs1.nocache.js" | sort -u)
if [[ ${#PERMS[@]} -eq 0 ]]; then
  echo "ERROR: could not parse permutation hashes from nocache.js" >&2
  exit 1
fi
echo "vendor-circuitjs: found ${#PERMS[@]} GWT permutations"
for h in "${PERMS[@]}"; do
  fetch "$GWT_DIR/$h.cache.js" "$DEST/$GWT_DIR/$h.cache.js"
done

# Fontello icon font (referenced by circuitjs.html as font/fontello.css).
fetch "font/fontello.css" "$DEST/font/fontello.css"
# fontello.css declares @font-face src urls; pull each referenced file.
mapfile -t FONT_FILES < <(grep -oE "fontello\.[a-z0-9?#=]+" "$DEST/font/fontello.css" | sed 's/[?#].*//' | sort -u)
for f in "${FONT_FILES[@]}"; do
  fetch "font/$f" "$DEST/font/$f" || echo "  (skip font/$f — optional)"
done

# Rewrite the one external <script> reference (Dropbox dropins.js) so the page
# stays fully offline-capable. We comment it out — Dropbox import is a CircuitJS
# feature we don't need for the tutorial.
if grep -q "www.dropbox.com/static/api/2/dropins.js" "$DEST/circuitjs.html"; then
  sed -i 's|<script[^>]*src="https://www\.dropbox\.com/static/api/2/dropins\.js"[^>]*>|<!-- dropbox dropins removed for offline use --><script data-removed="dropbox">|' "$DEST/circuitjs.html"
  echo "vendor-circuitjs: stripped external dropbox dropins.js reference"
fi

# License + notice — regenerated every run so they always match the snapshot.
echo "vendor-circuitjs: fetching COPYING.txt (GPLv2) from source repo"
curl -fsSL "$SOURCE_REPO_RAW/COPYING.txt" -o "$DEST/LICENSE.txt"

cat > "$DEST/NOTICE.txt" <<EOF
CircuitJS by Paul Falstad and contributors.
Source:   https://github.com/pfalstad/circuitjs1
Upstream: $UPSTREAM
Licensed under GPL v2 (see LICENSE.txt).
Vendored on $(date -u +%Y-%m-%d) for offline use in the electronics-tutorial
companion project. No modifications to the simulator runtime; only the external
Dropbox <script> reference in circuitjs.html was disabled so the page loads
without network access.
EOF

# Summary.
SIZE=$(du -sh "$DEST" | cut -f1)
HTML_OK=$( [[ -f "$DEST/circuitjs.html" ]] && echo yes || echo no )
NOCACHE_OK=$( [[ -f "$DEST/$GWT_DIR/circuitjs1.nocache.js" ]] && echo yes || echo no )
PERM_COUNT=$(ls "$DEST/$GWT_DIR"/*.cache.js 2>/dev/null | wc -l)
EXT_REFS=$(grep -cE 'src="https?:' "$DEST/circuitjs.html" || true)

cat <<EOF

vendor-circuitjs: done.
  destination:        $DEST
  total size:         $SIZE
  circuitjs.html:     $HTML_OK
  circuitjs1.nocache.js: $NOCACHE_OK
  GWT permutations:   $PERM_COUNT (.cache.js files)
  external script refs in circuitjs.html: $EXT_REFS (should be 0 for full offline)
  LICENSE.txt + NOTICE.txt: regenerated

Test offline: open file://$DEST/circuitjs.html in a browser, or
  npx serve $REPO_ROOT/public  and visit http://localhost:3000/circuitjs/circuitjs.html
EOF
